server:
  port: 3000

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/url_shortener_dev
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    org.springframework.web: ERROR
    mx.jovannypcg.urlshortener: DEBUG

